            ;function wca(a){return cb(a)}var xca={};function v5(a){var b=a.name;return mg(b)?kf.j(ll.v(B([a]))):kf.j(b)}if("undefined"===typeof SZ||"undefined"===typeof xca||"undefined"===typeof w5){var w5,yca=ji(Jh),zca=ji(Jh),Aca=ji(Jh),Bca=ji(Jh),Cca=v.l(Jh,nN,Fl.C?Fl.C():Fl.call(null));w5=new Rl(kf.h("lambdaisland.data-printers","type-name-pprint-dispatch"),ai.h(v5,rd),Cca,yca,zca,Aca,Bca)}w5.Ra(null,Sl,function(a){return ze(Xc,ll.v(B([a])))});
b4=function(a){var b=a instanceof pj;b||(b=(b=null!=a?a.G&32768||Wc===a.Ld?!0:a.G?!1:qd(ge,a):qd(ge,a))?b:a instanceof jf||Ag(a)||tg(a)||vg(a)||og(a)||null==a);return b?h5.j?h5.j(a):h5.call(null,a):w5.j?w5.j(a):w5.call(null,a)};function Dca(a,b,c){Pl(a,b,c)}function Eca(a,b,c){a.prototype.na=Wc;a.prototype.V=function(d,e,f){ze(e,["#",m.j(b)," "].join(""));return hl(new O(null,1,5,R,[c.j?c.j(this):c.call(null,this)],null),e,f)}}
function Fca(a,b,c){Dca(w5,kf.j(v5(a)),function(d){ze(Xc,["#",m.j(b)," "].join(""));return k4(c.j?c.j(d):c.call(null,d))})};var x5;function y5(a,b){if(null!=a&&null!=a.qh)a=a.qh(a,b);else{var c=y5[qa(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=y5._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw sd("StringSeparator.split",a);}return a}RegExp.prototype.qh=function(a,b){return zS(b,this)};y5.string=function(a,b){return zS(b,a)};
function Gca(a){switch(a){case "0":case "1":case "2":case "3":case "4":case "5":case "6":case "7":case "8":case "9":return ls;case "-":case "_":case " ":case "\t":case "\n":case "\x0B":case "\f":case "\r":return tr;case "a":case "b":case "c":case "d":case "e":case "f":case "g":case "h":case "i":case "j":case "k":case "l":case "m":case "n":case "o":case "p":case "q":case "r":case "s":case "t":case "u":case "v":case "w":case "x":case "y":case "z":return AH;case "A":case "B":case "C":case "D":case "E":case "F":case "G":case "H":case "I":case "J":case "K":case "L":case "M":case "N":case "O":case "P":case "Q":case "R":case "S":case "T":case "U":case "V":case "W":case "X":case "Y":case "Z":return Ho;
default:return bu}}function Hca(a){for(var b=Ei(Gca,a),c=a.length,d=Ie($f),e=0,f=0;;){var g=f+1,n=function(p,r){return function(t){return t>r?wh.h(p,a.substring(r,t)):p}}(d,e,f,g,b,c);if(f>=c)return(c=C(Ke(n(f))))?c:new O(null,1,5,R,[""],null);y.h(Of(b,f),tr)?(d=n(f),f=e=g):function(){var p=hj.h(b,f),r=L(p,0),t=L(p,1);p=L(p,2);return Gh.h(r,Ho)&&y.h(t,Ho)||Gh.h(r,ls)&&y.h(t,ls)||y.h(r,Ho)&&y.h(t,Ho)&&y.h(p,AH)}()?(d=n(g),f=e=g):f=g}}var z5;
"undefined"===typeof x5&&(x5=function(a){this.Yk=a;this.G=393216;this.L=0},x5.prototype.U=function(a,b){return new x5(b)},x5.prototype.T=function(){return this.Yk},x5.prototype.qh=function(a,b){return Hca(b)},x5.ab=!0,x5.Oa="camel-snake-kebab.internals.string-separator/t_camel_snake_kebab$internals$string_separator21329",x5.pb=function(a){return ze(a,"camel-snake-kebab.internals.string-separator/t_camel_snake_kebab$internals$string_separator21329")});z5=new x5(Jh);var A5=function A5(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return A5.v(arguments[0],arguments[1],arguments[2],arguments[3],4<c.length?new of(c.slice(4),0,null):null)};A5.v=function(a,b,c,d,e){e=Eh(e);e=v.l(e,ON,z5);return(d=C(y5(e,d)))?(e=C(d),d=E(e),e=F(e),wS(c,Uf(a.j?a.j(d):a.call(null,d),oi.h(b,e)))):""};A5.H=4;A5.I=function(a){var b=E(a),c=F(a);a=E(c);var d=F(c);c=E(d);var e=F(d);d=E(e);e=F(e);return this.v(b,a,c,d,e)};function B5(a,b){if(null!=a&&null!=a.ph)a=a.ph(a,b);else{var c=B5[qa(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=B5._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw sd("AlterName.alter-name",a);}return a}B5.string=function(a,b){return b.j?b.j(a):b.call(null,a)};w.prototype.ph=function(a,b){if(l(hh(this)))throw Wl("Namespaced keywords are not supported",new k(null,1,[PL,this],null));a=ih.j;var c=jh(this);b=b.j?b.j(c):b.call(null,c);return a.call(ih,b)};
jf.prototype.ph=function(a,b){if(l(hh(this)))throw Wl("Namespaced symbols are not supported",new k(null,1,[PL,this],null));a=kf.j;var c=jh(this);b=b.j?b.j(c):b.call(null,c);return a.call(kf,b)};function Ica(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;return Jca(arguments[0],1<b.length?new of(b.slice(1),0,null):null)}function Jca(a,b){return B5(a,function(c){return mf.v(A5,xS,wca,"",c,B([b]))})}var C5=function C5(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return C5.v(arguments[0],1<c.length?new of(c.slice(1),0,null):null)};C5.v=function(a,b){return ih.j(mf.v(A5,xS,xS,"-",jh(a),B([b])))};C5.H=1;
C5.I=function(a){var b=E(a);a=F(a);return this.v(b,a)};function D5(a,b,c){Eca(a,b,c);Fca(a,b,c)}function E5(a,b,c){D5(a,b,function(d){return xd(function(e,f){var g=dg.l;var n=f instanceof w?jh(f):f;n=null!=d&&n in d?d[n]:void 0;return g.call(dg,e,f,n)},Jh,c)})}
var F5=function F5(a){if("string"===typeof a)return a;if(a instanceof Text)return a.data;var c=new O(null,1,5,R,[ih.j(xS(a.tagName))],null);return di.l(function(){var d=C(a.getAttributeNames());return d?Zf.h(c,di.l(Jh,oi.j(Rk(C5,function(e){e=a.getAttribute(e);return"string"===typeof e&&250<e.length?[e.substring(0,250),"..."].join(""):e})),d)):c}(),oi.j(F5),a.childNodes)};D5(Text,Text,function(a){return a.data});D5(Element,uN,F5);D5(DocumentFragment,Jw,function(a){return oi.h(F5,a.children)});
D5(HTMLDocument,zF,function(a){return new k(null,1,[WF,a.documentElement],null)});D5(XMLDocument,CR,function(a){return new k(null,1,[WF,a.documentElement],null)});D5(Document,XE,function(a){return new k(null,1,[WF,a.documentElement],null)});E5(Window,Kt,new O(null,5,5,R,[yO,TC,xz,Fu,qs],null));D5(Location,KO,m);D5(HTMLCollection,OF,function(a){return di.h($f,a)});D5(NodeList,RA,function(a){return di.h($f,a)});
"undefined"!==typeof KeyboardEvent&&E5(KeyboardEvent,Rr,new O(null,10,5,R,[W,LI,xr,yy,Qt,xq,Xs,oH,yO,$J],null));"undefined"!==typeof TouchEvent&&(E5(TouchEvent,EL,new O(null,8,5,R,[W,Qt,Ls,yy,xq,Xs,CL,ny],null)),E5(Touch,Jz,new O(null,8,5,R,[QI,az,JE,rr,QR,yt,ZP,XL],null)),D5(TouchList,iu,ai.h(cj,C)));E5(PointerEvent,fP,new O(null,11,5,R,[W,TH,Qw,fR,Fp,Cv,Iw,Ru,Zy,VJ,pu],null));var G5=new O(null,15,5,R,[W,Qt,Ps,Cp,rr,QR,yy,xq,Jx,mR,KB,tz,az,JE,Xs],null);E5(MouseEvent,WE,G5);
E5(WheelEvent,vs,Zf.v(G5,vu,B([gE,jO,JR])));E5(DragEvent,Go,Zf.h(G5,BQ));Node.prototype.Ud=function(a,b){return this.appendChild(b)};var Kca=new k(null,6,"svg http://www.w3.org/2000/svg xhtml http://www.w3.org/1999/xhtml xlink http://www.w3.org/1999/xlink rdf http://www.w3.org/1999/02/22-rdf-syntax-ns# cc http://creativecommons.org/ns# dc http://purl.org/dc/elements/1.1/".split(" "),null);
function H5(a,b,c){var d=Ica(jh(b)),e;if(e=b instanceof w)e=hh(b),e=l(e)?!0:e;if(Bg(e))return a.setAttributeNS(v.h(Kca,hh(b)),d,c);e=y;var f=e.h;var g=jh(b).substring(0,3);if(f.call(e,"on-",g))return a[xS(d)]=c;if(y.h(UG,b)&&pg(c))return a.setAttribute("class",wS(" ",c));if(y.h(OB,b)&&tg(c))for(b=C(c),d=null,f=e=0;;)if(f<e)g=d.aa(null,f),c=L(g,0),g=L(g,1),a.style.setProperty(jh(c),g),f+=1;else if(b=C(b))wg(b)?(d=Pe(b),b=Qe(b),c=d,e=J(d),d=c):(d=E(b),c=L(d,0),g=L(d,1),a.style.setProperty(jh(c),g),
b=F(b),d=null,e=0),f=0;else return null;else return a.setAttribute(d,c)};var Lca={},Mca={};console.log(ll.v(B([new k(null,3,[TD,"forecastle",Gv,"2022-01-18T17:10:36.421513",dQ,"eedf33a9"],null)])));var Nca=new O(null,2,5,R,["vimeo.com","youtube.com"],null);function I5(){var a=J5,b=parseInt(a.height)/parseInt(a.width)*100,c=a.parentNode,d=document.createElement("div");d.className="video-wrapper";d.style.paddingBottom=[m.j(b),"%"].join("");c.insertBefore(d,a);a.remove();d.appendChild(a);a.removeAttribute("height");a.removeAttribute("width")}
if("undefined"===typeof SZ||"undefined"===typeof Lca||"undefined"===typeof Mca||"undefined"===typeof Oca)var Oca=function(){function a(f){if(l(f.target.classList.contains("project-discovery_parts__selected")))return null;b.classList.toggle("project-discovery_parts__selected");c.classList.toggle("project-discovery_parts__selected");d.classList.toggle("project-discovery_parts__hidden");return e.classList.toggle("project-discovery_parts__hidden")}var b=document.querySelector(".show-notes-button"),c=
document.querySelector(".transcript-button"),d=document.querySelector(".show-notes-container"),e=document.querySelector(".transcript-container");return l(l(b)?l(c)?l(d)?e:d:c:b)?(b.addEventListener("click",a),c.addEventListener("click",a)):null}();
a:{var K5,Pca=oi.h(function(a){return['iframe[src*\x3d"',m.j(a),'"]'].join("")},Nca);K5=wS(",",Pca);for(var L5=C(B(document.querySelectorAll(K5))),M5=null,N5=0,O5=0;;)if(O5<N5){var J5=M5.aa(null,O5);I5();O5+=1}else{var P5=C(L5);if(P5){var Q5=P5;if(wg(Q5)){var R5=Pe(Q5),Qca=Qe(Q5),Rca=R5,Sca=J(R5);L5=Qca;M5=Rca;N5=Sca}else J5=E(Q5),I5(),L5=F(Q5),M5=null,N5=0;O5=0}else break a}}function S5(a,b){l(b)?a.style.removeProperty("display"):H5(a,OB,new k(null,1,[hK,"none"],null))}
var T5=document.querySelector("#filter-box input"),U5=document.querySelector("#toggle-freebies");function V5(a){var b=xS(T5.value),c=l(U5)?Zh(new Ck(null,new k(null,1,["toggled",null],null),null),U5.classList):U5;return(od(c)||-1!=a.textContent.indexOf("Freebie"))&&(Ra(null==b?"":String(b))||-1!=xS(a.textContent).indexOf(b))}
l(T5)&&H5(T5,HM,function(){for(var a=C(document.querySelectorAll(".filterable")),b=null,c=0,d=0;;)if(d<c){var e=b.aa(null,d);S5(e,V5(e));d+=1}else if(a=C(a))b=a,wg(b)?(a=Pe(b),d=Qe(b),b=a,c=J(a),a=d):(a=E(b),S5(a,V5(a)),a=F(b),b=null,c=0),d=0;else break;a=C(document.querySelectorAll(".filterable-container"));b=null;for(e=d=0;;)if(e<d){var f=b.aa(null,e);S5(f,C(Di.h(function(){return function(n){return y.h("none",n.style.display)}}(a,b,d,e,f),f.querySelectorAll(".filterable"))));e+=1}else{var g=C(a);
if(g)c=g,wg(c)?(a=Pe(c),d=Qe(c),b=a,c=J(a),a=d,d=c):(f=E(c),S5(f,C(Di.h(function(){return function(n){return y.h("none",n.style.display)}}(a,b,d,e,f,c,g),f.querySelectorAll(".filterable")))),a=F(c),b=null,d=0),e=0;else return null}});
l(U5)&&H5(U5,IA,function(){var a=U5.classList,b=Zh(new Ck(null,new k(null,1,["toggled",null],null),null),a);l(b)?a.remove("toggled"):a.add("toggled");a=C(document.querySelectorAll(".filterable"));b=null;for(var c=0,d=0;;)if(d<c){var e=b.aa(null,d);S5(e,V5(e));d+=1}else if(a=C(a))b=a,wg(b)?(a=Pe(b),c=Qe(b),b=a,e=J(a),a=c,c=e):(e=E(b),S5(e,V5(e)),a=F(b),b=null,c=0),d=0;else return null});var W5=document.querySelector("#view_password");
l(W5)&&H5(W5,hN,function(a){return H5(document.querySelector("#password"),W,l(a.target.checked)?"input":"password")});